### ISSUE TITLE
WARNING: Slave does not support changing the PDO mapping!

### ISSUE THREAD

**Issue by alex-controlx** [STECHOQ/etherlab-nodejs#3]
Running the package produces a number of `WARNING`s in `tail -f /var/log/syslog | grep EtherCAT`
```
Dec 20 14:45:37 raspberrypi kernel: [11622.362572] EtherCAT WARNING 0-0: Slave does not support changing the PDO mapping!
Dec 20 14:45:37 raspberrypi kernel: [11622.362581] EtherCAT WARNING 0-0: Currently mapped PDO entries: 0x2000:00/8 0x200C:00/8 0x2001:00/16 0x2002:00/16 0x200F:00/8 0x2010:00/8. Entries to map: 0x2000:00/8 0x2001:00/16 0x2002:00/16 0x200C:00/8 0x200F:00/8 0x2010:00/8
Dec 20 14:45:37 raspberrypi kernel: [11622.362714] EtherCAT WARNING 0-0: Slave does not support changing the PDO mapping!
Dec 20 14:45:37 raspberrypi kernel: [11622.362719] EtherCAT WARNING 0-0: Currently mapped PDO entries: 0x3000:00/16 0x3001:00/8 0x3006:00/8 0x3002:00/16 0x3003:00/16. Entries to map: 0x3000:00/16 0x3001:00/8 0x3002:00/16 0x3003:00/16 0x3006:00/8
```

Sorting slaves PDOs at
[https://github.com/STECHOQ/etherlab-nodejs/blob/65c403f74939c0e99e833cd0d0d904a7b274505c/src/include/config_parser.cpp#L279](https://github.com/STECHOQ/etherlab-nodejs/blob/65c403f74939c0e99e833cd0d0d904a7b274505c/src/include/config_parser.cpp#L279)
messes up with the mapping.

I would ignore the warnings if it would work. It writes to wrong registers and it doesn't work. For example `0x2000` is the motor run, which does work. But `0x200C` is the speed setpoint and when remapped it does not work.

Current workaround is to modify `node_modules/etherlab-nodejs/src/include/config_parser.cpp` as such:
```javascript
// qsort(*slave_entries, *slave_length, sizeof(slaveEntry), _slave_entries_sort_asc);
```
and run `npm rebuild`.

Can be the sorting be the option like this?
```javascript
const configPath = './slaves.json';
const frequency_Hz = 1000;
const isSorted = false;

const ecatMaster = new __etherlab(configPath, frequency_Hz, isSorted);
```

Or sort the `position`s only?

**Comment by iqrok** [comment]
okay, I'll try to move the sorting from cpp to node.js, so it won't mess up with the pdo mapping

**Comment by iqrok** [comment]
I created [this branch](https://github.com/STECHOQ/etherlab-nodejs/tree/sorting-is-optional) to make sorting to be optional. the slaves won't be sorted by default.

if for some reason, qsort need to be executed, then the third parameter must be '__true__', otherwise qsort won't be executed
```javascript
const etherlab = new __etherlab(config, frequency, true);
```

the idea of sorting the domains was to make domain's index reflects the physical position of ethercat slaves. but since we have already had this method,

```javascript
write(position, index, subindex, value)
```

then I simply added this new method

```javascript
read(position, index, subindex)
```

with those 2 methods, IMO, the domain's indexes become irrelevant because index is no longer used for reading or writing domain's value. It's only used internally by the library.

can you try it first, before I merge with the main branch?

I did the test with the codes below
```javascript
const __etherlab = require('..');

const config = __dirname + '/slaves.sample.json';
const frequency = 2500;

const etherlab = new __etherlab(config, frequency);

let isRunning = 0;

const values = [0x00, 0x1ff0];
let index = 0;

function write(){
	etherlab.write(1,0x7000,0x01, values[index]);
	etherlab.write(1,0x7010,0x01, 0x1ff);
	etherlab.write(1,0x7020,0x01, values[index]);
	etherlab.write(1,0x7030,0x01, 0xff);

	index ^= 1;
}

function read(){
	console.log(
		`Pos 1 ${(0x7000).toString(16)}:0x01`, '=>', etherlab.read(1,0x7000,0x01), '\n',
		`Pos 1 ${(0x7010).toString(16)}:0x01`, '=>', etherlab.read(1,0x7010,0x01), '\n',
		`Pos 1 ${(0x7020).toString(16)}:0x01`, '=>', etherlab.read(1,0x7020,0x01), '\n',
		`Pos 1 ${(0x7030).toString(16)}:0x01`, '=>', etherlab.read(1,0x7030,0x01), '\n',
	);

	console.log('==============================================');
}

etherlab.on('data', (data, latency) => {});

etherlab.on('state', current => {
	console.log('master\'s current state ', current);
});

etherlab.on('ready', async () => {
	const domain = await etherlab.getDomain();

	setInterval(() => {
		write();
	}, 1000);

	setInterval(() => {
		read();
	}, 1000);
});

etherlab.on('error', error => {
	console.error(error);
});

etherlab.start();
```

**Comment by alex-controlx** [comment]
Thank you for doing this. I just tested and no more warnings `Slave does not support changing the PDO mapping!`.

My test code below:
```javascript
const __etherlab = require('.');

const config = __dirname + '/slaves.json';
const frequency = 2500;

const etherlab = new __etherlab(config, frequency);

const values = [500, 1000];
let index = 0;

function write() {
    // run motor
    etherlab.write(0,0x2000,0x00, 1);

    // change speed - this is where the problem was before!
    etherlab.write(0,0x2001,0x00, values[index]);
    index ^= 1;
}

function read(){
    console.log(
        `Pos 0x2000:0x01 => ${etherlab.read(0,0x2000,0x00)}\n` +
        `Pos 0x2001:0x01 => ${etherlab.read(0,0x2001,0x00)}`
    );
    console.log('==============================================');
}

etherlab.on('state', current => {
    console.log('master\'s current state ', current);
});

etherlab.on('ready', () => {
    setInterval(() => {
        write();
        // etherlab.write needs a callback on finish writing
        setTimeout(read, 100);
    }, 3000);
});

etherlab.on('error', error => {
    console.error(error);
});

etherlab.start();

```

and this is the console output:
```
Using priority 99
sched_setscheduler failed: Operation not permitted
master's current state  2
master's current state  8
Pos 0x2000:0x01 => 1
Pos 0x2001:0x01 => 500
==============================================
Pos 0x2000:0x01 => 1
Pos 0x2001:0x01 => 1000
==============================================
```

Changing to `sort` like this: `const etherlab = new __etherlab(config, frequency, true);` produces the `WARNING` and motor doesn't spin. However, logs the same console output.

So it works as intended. @iqrok feel free to close it when merged to the master.

**Comment by alex-controlx** [comment]
Create a simple step list on how to install the library from scratch: [Setup EtherCAT master on RPI 4 with NodeJS (using Etherlab)](https://bitbucket.org/alex-OC/workspace/snippets/gBrxbb)
